name: Deploy
on:
    push:
      branches:
        - master
jobs:
    deploy:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Install sshpass
          run: sudo apt-get install sshpass

        - name: Copy docker-compose.yml to droplet
          run: sshpass -v -p ${{ secrets.DROPLET_PASSWORD }} scp -r -o StrictHostKeyChecking=no ./src root@${{ secrets.DROPLET_IP }}:/tinyhousess/src
        - name: Copy docker-compose.yml to droplet
          run: sshpass -v -p ${{ secrets.DROPLET_PASSWORD }} scp -r -o StrictHostKeyChecking=no ./public root@${{ secrets.DROPLET_IP }}:/tinyhousess/public
        - name: Copy docker-compose.yml to droplet
          run: sshpass -v -p ${{ secrets.DROPLET_PASSWORD }} scp -r -o StrictHostKeyChecking=no ./package.json root@${{ secrets.DROPLET_IP }}:/tinyhousess/package.json
        - name: Copy docker-compose.yml to droplet
          run: sshpass -v -p ${{ secrets.DROPLET_PASSWORD }} scp -r -o StrictHostKeyChecking=no ./package-lock.json root@${{ secrets.DROPLET_IP }}:/tinyhousess/package-lock.json
        - name: Deploy
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.DROPLET_IP }}
            command_timeout: 20m
            username: root
            password: ${{ secrets.DROPLET_PASSWORD }}
            script: |
              pkill -f react &>/dev/null || true
              cd /tinyhousess
              npm install
              nohup npm run start &

              # Wait a moment for the process to start
              sleep 5

              # Check if the process is running
              if pgrep -f "npm run start" > /dev/null; then
                echo "Successfully started the application."
              else
                echo "Error: The application failed to start."
                exit 1
              fi

             