name: Deploy
on:
    push:
      branches:
        - master
jobs:
    deploy:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Install sshpass
          run: sudo apt-get install sshpass

        - name: Copy docker-compose.yml to droplet
          run: sshpass -v -p ${{ secrets.DROPLET_PASSWORD }} scp -r -o StrictHostKeyChecking=no ./src root@${{ secrets.DROPLET_IP }}:/tinyhousess
        - name: Copy docker-compose.yml to droplet
          run: sshpass -v -p ${{ secrets.DROPLET_PASSWORD }} scp -r -o StrictHostKeyChecking=no ./public root@${{ secrets.DROPLET_IP }}:/tinyhousess
        - name: Copy docker-compose.yml to droplet
          run: sshpass -v -p ${{ secrets.DROPLET_PASSWORD }} scp -r -o StrictHostKeyChecking=no ./package.json root@${{ secrets.DROPLET_IP }}:/tinyhousess/package.json
        - name: Copy docker-compose.yml to droplet
          run: sshpass -v -p ${{ secrets.DROPLET_PASSWORD }} scp -r -o StrictHostKeyChecking=no ./package-lock.json root@${{ secrets.DROPLET_IP }}:/tinyhousess/package-lock.json
        - name: Deploy
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.DROPLET_IP }}
            username: root
            password: ${{ secrets.DROPLET_PASSWORD }}
            script: |
             pgrep -f react | xargs kill
             cd /tinyhousess
             npm install
             npm start
             